server:
  port: 8081

spring:
  application:
    name: dubbo-consumer

dubbo:
  registry:
    address: zookeeper://sunhomo.cn:2181,sunhomo.cn:2182,sunhomo.cn:2183
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false